### ISSUE TITLE
Authentication Bugs on MacOS and Linux

### ISSUE THREAD

**Issue by LiamBurke24** [DataONEorg/rdataone#192] opened 2017-06-15 21:08 UTC
@mbjones, Mike Dietze and I have run into a few authentication bugs in the current version of dataone. For example:
```
query(cn, solrQuery = "id:10.6073/pasta/6b03a068eb72af9b2ba14d633c9cb60c", encode = FALSE, as = "data.frame")
```
and 
```
am <- AuthenticationManager()
getTokenInfo(am)
```
both return:
```
Error in unlist(strsplit(authToken, "\\."))[[2]] : subscript out of bounds
```
This error persists on multiple **linux** operating systems and on **macOS Sierra** despite our attempts to troubleshoot the authentication token. 

We would both appreciate you taking a look at this.

**Comment by amoeba** [comment] 2017-06-15 22:14
Hey @LiamBurke24, sorry you're having trouble. I'm happy to help.

Can you please paste minimum reproducible examples for each or your two examples? I can't reproduce your error message.

**Comment by LiamBurke24** [comment] 2017-06-15 22:27
Hey @amoeba! Thank you! Sure! 

In attempting to query a doi: 
```
library(dataone)
options(dataone_token = "MIIGHTCCBQWgAwIBAgIDK+ ... [abbreviated]")
query(cn, solrQuery = "id:10.6073/pasta/6b03a068eb72af9b2ba14d633c9cb60c", 
          encode = FALSE, as = "data.frame")
```

in attempting to get token info 
```
library(dataone)
options(dataone_token = "MIIGHTCCBQWgAwIBAgIDK+ ... [abbreviated]")
am <- AuthenticationManager()
getTokenInfo(am)
```

please let me know if there is any other information that you need!

**Comment by amoeba** [comment] 2017-06-15 23:02
Thanks @LiamBurke24. I can't reproduce the issue on macOS Sierra or Ubuntu Linux. Maybe it's something specific to your environments.

Can you please paste the output of running `sessionInfo()` from an R console? Or better yet, if you have the devtools package installed, the output from `devtools::session_info()`?

Thanks

**Comment by LiamBurke24** [comment] 2017-06-15 23:26
Thank YOU @amoeba. Here ya go. The three linux machines and my local machine (rstudio) in order. 

From Pecan1: ![screen shot 2017-06-15 at 6 19 05 pm](https://user-images.githubusercontent.com/29068693/27205559-288e8122-51f7-11e7-800c-b3fb82842b0e.png)

From Pecan2: 
![screen shot 2017-06-15 at 6 20 23 pm](https://user-images.githubusercontent.com/29068693/27205589-58b7c246-51f7-11e7-8607-3b82851a011f.png)

From test-pecan: 
![screen shot 2017-06-15 at 6 22 34 pm](https://user-images.githubusercontent.com/29068693/27205649-a5be7396-51f7-11e7-9a8a-0f6f80cf57ee.png)

From my local R-studio: 
![screen shot 2017-06-15 at 6 24 05 pm](https://user-images.githubusercontent.com/29068693/27205699-f06e57a8-51f7-11e7-9b4f-005cf5ab46a8.png)

**Comment by gothub** [comment] 2017-06-15 23:41
@LiamBurke24 The portion of the token that you show looks a little unusual. Where did you generate it from? 

The R client expects that the token has three '.' in the string that delimit the
3 different portions of the token. This is the standard
format for the type of tokens we are using (https://en.wikipedia.org/wiki/JSON_Web_Token).

Does the token string have three '.' characters?

BTW the R client needs to handle the case of an invalid token better, I'll enter an issue for this.

**Comment by LiamBurke24** [comment] 2017-06-16 00:26
Thanks @gothub, it doesn't look like there are three '.' characters in the token. Unfortunately, I can't remember how I generated the token. I can't seem to retrace my steps through the documentation. I recall following a prompt to generate the token after running a script while logged out. If there is a recommended method, I'd gladly regenerate the token and try again. Thanks!

**Comment by LiamBurke24** [comment] 2017-06-16 00:41
I don't remember the command, but it opened the url: https://cilogon.org/?skin=DataONE. I logged in under my university, downloaded some sort of java file, opened that file in java on my local machine, then copied the link that appeared in the java client into my browser and was presented with a plain text page with a private key and a certificate. I copied and pasted the certificate into R as the token. I hope this helps.

**Comment by gothub** [comment] 2017-06-16 00:50
@LiamBurke24 Instructions for generating the new authentication token can be found at
https://github.com/DataONEorg/rdataone/blob/master/vignettes/dataone-overview.Rmd
These docs are slightly out of date, ignore the "Click the "Apps" menu item." step. Let me 
know if any of the many steps aren't clear.

**Comment by LiamBurke24** [comment] 2017-06-16 01:55
@gothub That did the trick! Thank you so much! Thank you and @amoeba for responding so quickly.

**Comment by amoeba** [comment] 2017-06-16 06:07
Glad @gothub got you squared away (Thanks @gothub)!

**Comment by LiamBurke24** [comment] 2017-06-16 16:03
Hi @amoeba and @gothub! Im reopening this issue because it has reared its head in another bizarre way. 

I am attempting to run the following code on the same machines as before and running into the bug at a different stage. Let me show you: 

```
library(dataone)
data_one_token <- options(dataone_token = "eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJDTj1MaWFtI ... "
cn <- CNode("PROD")
result <- query(cn, solrQuery = "id:10.6073/pasta/6b03a068eb72af9b2ba14d633c9cb60c", encode = FALSE, as = "data.frame", parse = FALSE)

d1c <- D1Client("PROD", "urn:node:CDL")
pid <- result[1,"id"]
data_one_token
obj <- getDataObject(d1c, pid) # code breaks here and presents the error below:
data <- getData(obj)
```

```
Your login certificate is missing or unreadable. You must login again via CILogon using 'dataone::downloadCert(CertificateManager())'
Attempting to call as public user without being authenticated.
```

This message appears even after updating the authentication per your guidelines yesterday. Also of note is the prompt to run `dataone::downloadCert(CertificateManager())`. Following this prompt leads to an invalid authentication token error that I described above. 

Again, I'd truly appreciate your insight.

**Comment by gothub** [comment] 2017-06-16 16:32
@LiamBurke24 Support for authentication tokens began with version 2 of the DataONE Member Node API. It looks like CDL is still at version 1:

```
https://cn.dataone.org/cn/v2/node/urn:node:CDL
...
Services:	
Name	Version	Available
MNRead	v1	true
MNCore	v1	true
MNAuthorization	v1	false
...
```

For now, you can continue to use a certificate file, which is the supported authentication method
for DataONE  version 1 API, which you had already started  by navigating your browser to 'https://cilogon.org/?skin=DataONE'.  I'd be happy to walk you through this process, as there are a few steps involved.

Note that these certificate files do not work on later versions Mac OS X, or macOS, since 
Apple made changes to certificate handling that prevent our certificates from working.

**Comment by LiamBurke24** [comment] 2017-06-16 16:53
@gothub Ok, this makes sense. Thank you! Seeing as the V1 certificate is no longer compatible with the query function (as we ran into before) is there some way I can enter both certificates in the same code without confusing either the query function or the getDataObject function with the incorrect token?

**Comment by gothub** [comment] 2017-06-16 17:08
@LiamBurke24 Have you been able to recently create a certificate file? When you run the CILogin client, the window that comes up has the title "Download Certificate". This dialog box then 
tells you the location of the file that it downloads. These certificates expire after about 18 hours.

After the current certificate is copied to disk, you shouldn't have to do anything more to this
file, the R client should be able to find it. This certificate should work for query or any other
`dataone` package R function.

**Comment by LiamBurke24** [comment] 2017-06-16 17:59
Yes, I have. I created another certificate a couple of hours ago. Perhaps I am making an error in how I get the certificate? I copied the link from the java dialog box into a chrome browser and was taken to an html page with the certificate and a private key. I copied this certificate into R using options(dataone_token = "certificate"). Is this the proper method? It was unclear how I should have proceeded from the popup. Many thanks!

**Comment by gothub** [comment] 2017-06-16 19:17
@LiamBurke24 Ah, ok. I'm not familiar with this method of providing the certificate, usually a
Java client is started that securly copies the certificate to your local disk. The naming convention of the file is something like `/tmp/x509up_u501` where in my case the last three characters `501` is my Linux user id. You can manually create this file by first determining your user id by opening
a terminal window and typing

```
$ id
uid=501(slaughter) gid=20(staff) groups=20(staff),12(everyone)
```

and check for the value of `uid=`

Then, substituting your user id, create the file in `/tmp/x509up_u<your id here>` inserting the certificate, then the RSA key:

```
----BEGIN CERTIFICATE-----
MIIGzDCCBbSgAwIBAgIDA ...
-----BEGIN RSA PRIVATE KEY-----
MIIEowIBAAKCAQEAgSWOqtqY+ANqjy ... 
-----END RSA PRIVATE KEY-----
```

After you have done this, you can check the cert by typing 
```
getCertInfo(AuthenticationManager())
```

Hang in there, generating certificates can be frustrating, which is one of the reasons
why we started using authentication tokens!

**Comment by LiamBurke24** [comment] 2017-06-16 19:22
This makes sense @gothub. I am so grateful for your help in this matter!!!!

**Comment by LiamBurke24** [comment] 2017-06-16 19:49
Ok, so I think the java client installs the key automatically on my computer. However, when I try to run the script above, I get a fatal error warning when I get to the getDataObject line. Is this because I am operating on macOS sierra?

**Comment by gothub** [comment] 2017-06-16 20:05
The error that prints out when you try to use a certificate file on a mac is this:

```
 Error in curl::curl_fetch_memory(url, handle = handle) : 
  Problem with the local SSL certificate 
```

The certificate should work on Linux or Windows

**Comment by LiamBurke24** [comment] 2017-06-16 20:15
@gothub Ok. Explored running on Linux and I see that certificate manager is deprecated and will be removed in a future version. Perhaps I should try a different method of accessing the data as I am attempting to build a generalized doi ingest system. Any idea when certificates will be phased out for good?

**Comment by gothub** [comment] 2017-06-16 21:35
@LiamBurke24 We haven't set a date yet for dropping support for these certificate files, but 
I think the idea was to give member nodes enough time to upgrade to version 2 of the the
DataONE API. Is this a possibility for CDL? BTW, You don't need authentication if the datasets
you are accessing are publicly readable.

**Comment by csjx** [comment] 2017-06-17 01:20
@gothub @liamBurke24 Just to toss in my two cents: While DataONE is moving toward JWT authentication tokens for most end-user clients for better usability, I'm not convinced that we'll be deprecating X509 certificate-based authentication anytime soon.  I say this because it is the primary way that Member Nodes and Coordinating Nodes talk to each other in a machine to machine fashion.  These node certificates are more long-lived than the CILogon certificates (3 years vs 18 hours), but the authentication mechanism (via the SSL handshake) is identical.  We'll need to discuss the `v1` vs `v2` issue with Dave (@datadavev). Since CDL is using Metacat as their DataONE API implementation, they could probably upgrade fairly easily and start supporting `v2` and tokens (since Metacat supports them).

**Comment by LiamBurke24** [comment] 2017-06-19 22:04
Thanks @csjx and @gothub. Really appreciate you taking the time to walk me through this.

**Closed** 2017-06-19 22:04 UTC
