### ISSUE TITLE
Issue with getChecksum for private data package

### ISSUE THREAD

**Issue by eblondel** [DataONEorg/rdataone#262] opened 2020-10-16 13:06 UTC
Hello,

Thanks for this great package. I'm currently trying it to insert/update cycles over data packages, and at some point I moved out from the CRAN version to install the current Github dev version.

I've tried to apply ``getDataPackage`` method, but for the data resource attached to it, I got this error:

```r
Error in checksum$.attrs[["algorithm"]] : subscript out of bounds
```

Digging into the R code, i've identified this comes from the ``getChecksum`` function. For some unknown reason, I get an unauthorized GET request, which makes code break at https://github.com/DataONEorg/rdataone/blob/master/R/MNode.R#L307

My ``checksum`` object returned at line 304 looks like that:

```R
$description
[1] "READ not allowed on urn:uuid:f806756e-0fa3-11eb-a2e5-e5e202a27544 for subject[s]: public; "

$.attrs
     detailCode       errorCode            name 
         "1820"           "401" "NotAuthorized" 

```
I've then realized this was because the data package was set as private, and the getChecksum is always done without authorization. Shouldn't it use  ``auth_get`` instead native httr::GET ? so we can allow getting private data packages?

**Comment by mbjones** [comment] 2020-11-24 19:44
@eblondel this looks like a bug in error handling to me, so I will target it at the next release if we can reproduce it (help on a short [reprex](https://reprex.tidyverse.org/articles/articles/learn-reprex.html) would be useful. If we can't quickly reproduce it, we'll probably retarget it to 2.3.0.

**Comment by gothub** [comment] 2020-11-24 21:28
Thanks @eblondel for flagging this issue, and for providing the solution.

This problem has been resolved, such that authorized users can retrieve checksums for private content. 

Fixed in commit https://github.com/DataONEorg/rdataone/commit/5ad2b7df2eebf106c5ff17a42c2823b7eb66a5d4

**Closed by gothub** 2020-11-24 21:28 UTC
Labels: bug

**Comment by CDorich** [comment] 2020-11-24 21:29
I've tried unsubscribing from this list a few time, but keep getting the email. Can you unsubscribe me?

-Chris
________________________________

**Comment by mbjones** [comment] 2020-11-24 23:49
@CDorich we can not, only you can. The overall email notification settings are controlled in your github account settings. And the repository-specific settings are controlled via the `Watch` button at the top of each repository page.  Details of unsubscribing are in the GitHub docs: https://docs.github.com/en/free-pro-team@latest/github/managing-subscriptions-and-notifications-on-github/managing-your-subscriptions

**Comment by eblondel** [comment] 2020-11-25 13:16
Many thanks @gothub and @mbjones for this prompt fix, much appreciated!
